### ISSUE TITLE
ToDo/Wish List

### ISSUE THREAD

**Issue by nickzuber** [nickzuber/markup#4]
Here I'm going to outline a todo list for things we want to finish with Markup, and where we currently are:

- [ ] **Share feature**
  - [ ] Set up database for storing raw text
  - [ ] Set up microservice for interfacing database
  - [ ] Hook microservice up to 

- [ ] **Expand output**
  - [ ] Set up action/state routine for handling expanded view

- [x] **Local save**
  - [x] Hook local save up to browser localStorage
  - [x] Set up action/state routine for handling last saved

**Comment by nickzuber** [comment]
Holding off on the major parts of sharing for now, just want to keep it simple at first.
